---
- name: Add Apt Keys
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90 state=present

- name: Add repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free'

- name: Install spotify
  apt: name=spotify-client update_cache=yes state=latest
